name: publish

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "The run ID of the build that you want to publish"
        required: true
        type: number

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download binary distributions
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 #v4.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.run_id }}
          name: artifact-npm-binary-distributions
          path: ./npm-binary-distributions

      - name: Download main Node package
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 #v4.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.run_id }}
          name: artifact-pkg-node
          path: ./node-pkg

      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20.10.0"
          registry-url: "https://registry.npmjs.org"
          scope: "supabase"

      - name: Publish binary distrubutions
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          for tarball in ./npm-binary-distributions/*/*.tgz; do
            npm publish --provenance --access public "$tarball"
          done

      - name: Publish Node package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          for tarball in ./node-pkg/*.tgz; do
            npm publish --provenance --access public "$tarball"
          done
